tests: add set -e

diff --git a/test/envtest.in b/test/envtest.in
--- a/test/envtest.in
+++ b/test/envtest.in
@@ -1,6 +1,7 @@
-
 export TEST_ORIGIN=@srcdir@
 if [ x@EXEEXT@ = x.exe ]; then WINE=wine
 else WINE=""; fi
 export REQFLOW="$WINE ../reqflow@EXEEXT@"
 
+# test fails at first error
+set -e
